# Generated by Django 6.0.4 on 2026-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_options_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('canceled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
