# Generated by Django 6.0.4 on 2026-09-03 21:30

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='رمز متابعة الطلب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.get_file_path),
        ),
    ]
