# Generated by Django 6.0.4 on 2026-09-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_tracking_code_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='المدينة')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('active', models.BooleanField(default=True, verbose_name='مفعلة')),
            ],
            options={
                'verbose_name': 'منطقة توصيل',
                'verbose_name_plural': 'مناطق التوصيل',
                'ordering': ['city'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل'),
        ),
    ]
